wallpaper {
monitor = DP-2
path = ~/.config/hypr/theme/walls/
fit_mode = cover
timeout = 900
}

wallpaper {
monitor = HDMI-A-1
path = ~/.config/hypr/theme/walls/
fit_mode = cover
timeout = 900
}

splash = false