wallpaper {
monitor = $first
path = ~/.config/hypr/walls/
fit_mode = cover
timeout = $timeout
}

# Uncomment if using multi-monitor setup:
# wallpaper {
# monitor = $second
# path = ~/.config/hypr/walls/
# fit_mode = cover
# timeout = $timeout
# }
# wallpaper {
# monitor = $third
# path = ~/.config/hypr/walls/
# fit_mode = cover
# timeout = $timeout
# }

splash = false